const colors = require("tailwindcss/colors");
const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  theme: {
    extend: {
      width: {
        "cr-label-desktop": "50rem",
        "cr-label-1025": "30rem",
        "cr-label-ipad": "25rem",
        "cr-label-duo": "24rem",
        "cr-label-6s": "15rem",
        "cr-label-5s": "14rem",
        "cr-label-fold": "11.5rem",
        "flag-desktop": "22.5rem",
        "flag-6s": "18rem",
        "flag-5s": "16.5rem",
        "flag-fold": "15rem",
      },
      margin: {
        "10px": "10px",
      },
      outline: {
        default: ["3px solid #ffbf47"],
        amber: ["3px solid #ffbf47"],
        blue: ["3px solid theme(colors.blue.focus)"],
      },
      backgroundPosition: {
        "center-right-15px": "center right 15px",
      },
      inset: {
        "10px": "10px",
        "9px": "9px",
      },
      maxWidth: {
        prose: "75ch",
      },
      listStyleType: {
        disc: "disc",
        decimal: "decimal",
        circle: "circle",
      },
      colors: {
        current: "currentColor",
        red: {
          DEFAULT: "var(--gcds-color-red-700, #b10e1e)",
          default: "var(--gcds-color-red-700, #b10e1e)",
          100: "var(--gcds-color-red-100, #f3e9e8)",
          destructive: "var(--gcds-color-danger, #892406)",
          hover: "var(--gcds-color-red-900, #4E1504)",
        },
        purple: {
          ...colors.violet,
          DEFAULT: "#6300C7",
          default: "#6300C7",
        },
        white: {
          DEFAULT: "#FFF",
          default: "#FFF",
        },
        blue: {
          DEFAULT: "var(--gcds-color-blue-800, #26374A)",
          default: "var(--gcds-color-blue-800, #26374A)",
          focus: "var(--gcds-color-blue-focus, #303FC3)",
          100: "var(--gcds-color-blue-100, #B2E3FF)",
          hover: "var(--gcds-link-hover, #0535D2)",
          500: "var(--gcds-color-blue-500, #75b9e0)",
          light: "var(--gcds-color-blue-700, #335075)",
          700: "var(--gcds-color-blue-700, #335075)",
          dark: "var(--gcds-color-blue-800, #26374A)",
          800: "var(--gcds-color-blue-800, #26374a)",
          active: "var(--gcds-color-blue-900, #1B2736)",
        },
        gray: {
          DEFAULT: "var(--gcds-color-grayscale-50, #EEE)",
          default: "var(--gcds-color-grayscale-50, #EEE)",
          background: "var(--gcds-color-grayscale-50, #f4f4f4)",
          selected: "var(--gcds-color-grayscale-100, #e1e4e7",
          500: "var(--gcds-color-grayscale-300, #a0aec0)",
          600: "var(--gcds-color-grayscale-500, #718096)",
          text: "var(--gcds-color-grayscale-700, #585858)",
          700: "var(--gcds-color-grayscale-700, #4a5568)",
          800: "var(--gcds-color-grayscale-900, #2d3748)",
        },
        yellow: {
          ...colors.amber,
          default: "#ffbf47",
          DEFAULT: "#ffbf47",
          100: `var(--gcds-color-yellow-100, theme(colors.amber.100))`,
          500: `var(--gcds-color-yellow-500, theme(colors.amber.500))`,
        },
        green: {
          ...colors.emerald,
          default: "#00703C",
          DEFAULT: "#00703C",
          light: "var(--gcds-color-green-100, #ECF3EC)",
          500: `var(--gcds-color-green-500, theme(colors.emerald.500))`,
          darker: "var(--gcds-color-green-700, #005930)",
        },
        black: {
          default: "#000",
          DEFAULT: "#000",
          form: "#000",
        },
        transparent: "transparent",
      },
      fontSize: {
        badge: ["14px", "14px"],
        sm: ["var(--gcds-font-sizes-caption, 16px)", "var(--gcds-line-heights-caption, 22px)"],
        base: ["var(--gcds-font-sizes-text, 20px)", "var(--gcds-line-heights-text, 28px)"],
        p: ["var(--gcds-font-sizes-text, 20px)", "150%"],
        h5: ["var(--gcds-font-sizes-h5, 24px)", "var(--gcds-line-heights-h5, 30px)"],
        h3: ["var(--gcds-font-sizes-h3, 26px)", "var(--gcds-line-heights-h3, 32px)"],
        h2: ["var(--gcds-font-sizes-h2, 30px)", "var(--gcds-line-heights-h2, 38px)"],
        h1: ["var(--gcds-font-sizes-h1, 34px)", "var(--gcds-line-heights-h1, 44px)"],
        small_sm: ["12px", "14px"],
        small_base: ["16px", "22px"],
        small_p: ["16px", "22px"],
        small_h3: ["18px", "22px"],
        small_h2: ["20px", "28px"],
        small_h1: ["24px", "28px"],
      },
      zIndex: {
        "-1": "-1,",
        100: "100,",
      },
      borderWidth: {
        default: "1px",
        0: "0",
        1: "1px",
        1.5: "1.5px",
        2: "2px",
        2.5: "2.5px",
        3: "3px",
        4: "4px",
        5: "5px",
        8: "8px",
        sm: "0.0625rem",
        md: "0.125rem",
        lg: "0.25rem",
        xl: "0.375rem",
      },
      borderRadius: {
        sm: "var(--gcds-border-radius-sm, 0.125rem)",
        md: "var(--gcds-border-radius-md, 0.375rem)",
      },
      boxShadow: {
        default: "0 1px 3px rgba(0, 0, 0, 0.05);",
        result: "0px 0px 12px -2px rgba(0,0,0,0.4)",
        input: "inset 0 0 0 2px #0535d2",
        none: "var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)",
      },
    },
    container: {
      center: true,
    },
    fontFamily: {
      sans: ["Lato", ...defaultTheme.fontFamily.sans],
      body: ['"Noto Sans"'],
      mono: ["monospace"],
    },
    screens: {
      xxl: { max: "1200px" },
      xl: { max: "992px" },
      lg: { max: "768px" },
      md: { max: "550px" },
      sm: { max: "450px" },
      xs: { max: "320px" },
      xxs: { max: "290px" },
    },
  },
  content: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("@tailwindcss/line-clamp")],
};
