import readline from "node:readline";
import { unlink } from "node:fs/promises";
import { deleteForms } from "./cleanup/deleteForm.js";
// @ts-ignore
import output from "../output.json"; // This file is automatically generated once you have used the setup action.

async function main(): Promise<void> {
  try {
    const shouldDeleteForms = Boolean(
      await requestUserInput(
        `You are about to delete ${output.testForms.length} forms. Are you sure? (yes or no): `
      ).then((response) => (response === "yes" ? true : false))
    );

    if (shouldDeleteForms === false) return;

    const deletedForms = await deleteForms(output.testForms.map((f) => f.id));

    console.info(
      `${
        deletedForms.length === output.testForms.length
          ? `All ${deletedForms.length}`
          : `${deletedForms.length} out of ${output.testForms.length}`
      } forms have been deleted!`
    );

    await unlink("output.json");

    console.info("You are done! The 'output.json' file has been deleted.");
  } catch (error) {
    console.error(error);
  }
}

function requestUserInput(question: string): Promise<string> {
  const readlineInterface = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise<string>((resolve) =>
    readlineInterface.question(question, (response) => {
      readlineInterface.close();
      resolve(response);
    })
  );
}

main();
