export const options = [
  {
    name: "oag",
    urlEn: "https://www.oag-bvg.gc.ca/internet/English/admin_e_41.html",
    urlFr: "https://www.oag-bvg.gc.ca/internet/Francais/admin_f_41.html",
    logoEn: "/img/branding/oag-en.svg",
    logoFr: "/img/branding/oag-fr.png",
    logoTitleEn: "Office of the Auditor General of Canada",
    logoTitleFr: "Bureau du vérificateur général du Canada",
  },
  {
    name: "irb",
    urlEn: "https://irb.gc.ca/en",
    urlFr: "https://irb.gc.ca/fr",
    logoEn: "/img/branding/irb-en.svg",
    logoFr: "/img/branding/irb-fr.png",
    logoTitleEn: "Immigration and Refugee Board of Canada",
    logoTitleFr: "Commission de l'immigration et du statut de réfugié du Canada",
  },
  {
    name: "nbc",
    urlEn: "https://www.ccbn-nbc.gc.ca/en/",
    urlFr: "https://www.ccbn-nbc.gc.ca/en/",
    logoEn: "/img/branding/nbc-en.svg",
    logoFr: "/img/branding/nbc-fr.png",
    logoTitleEn: "The National Battlefields Commission",
    logoTitleFr: "Commission des champs de bataille nationaux",
  },
  {
    name: "cb-cda",
    urlEn: "https://cb-cda.gc.ca/en",
    urlFr: "https://cb-cda.gc.ca/fr",
    logoEn: "/img/branding/cb-cda.png",
    logoFr: "/img/branding/cb-cda.png",
    logoTitleEn: "Copyright Board of Canada",
    logoTitleFr: "Commission du droit d'auteur du Canada",
  },
  {
    name: "tsb",
    urlEn: "https://www.tsb.gc.ca/eng/",
    urlFr: "https://www.tsb.gc.ca/fra",
    logoEn: "/img/branding/tsb-en.png",
    logoFr: "/img/branding/tsb-fr.png",
    logoTitleEn: "Transportation Safety Board of Canada",
    logoTitleFr: "Bureau de la sécurité des transports du Canada",
  },
  {
    name: "cds",
    urlEn: "https://digital.canada.ca",
    urlFr: "https://numerique.canada.ca",
    logoEn: "/img/branding/cds-en.svg",
    logoFr: "/img/branding/cds-fr.png",
    logoTitleEn: "Canadian Digital Service",
    logoTitleFr: "Service numérique canadien",
  },
];
