export const options = [
  {
    name: "oag",
    urlEn: "https://www.oag-bvg.gc.ca/internet/English/admin_e_41.html",
    urlFr: "https://www.oag-bvg.gc.ca/internet/Francais/admin_f_41.html",
    logoEn: "/img/branding/oag-en.svg",
    logoFr: "/img/branding/oag-fr.svg",
    logoTitleEn: "Office of the Auditor General of Canada",
    logoTitleFr: "Bureau du vérificateur général du Canada",
  },
  {
    name: "irb",
    urlEn: "https://irb.gc.ca/en",
    urlFr: "https://irb.gc.ca/fr",
    logoEn: "/img/branding/irb-en.svg",
    logoFr: "/img/branding/irb-fr.svg",
    logoTitleEn: "Immigration and Refugee Board of Canada",
    logoTitleFr: "Commission de l'immigration et du statut de réfugié du Canada",
  },
  {
    name: "nbc",
    urlEn: "https://www.ccbn-nbc.gc.ca/en/",
    urlFr: "https://www.ccbn-nbc.gc.ca/en/",
    logoEn: "/img/branding/nbc-en.svg",
    logoFr: "/img/branding/nbc-fr.svg",
    logoTitleEn: "The National Battlefields Commission",
    logoTitleFr: "Commission des champs de bataille nationaux",
  },
  {
    name: "cb-cda",
    urlEn: "https://cb-cda.gc.ca/en",
    urlFr: "https://cb-cda.gc.ca/fr",
    logoEn: "/img/branding/cb-cda.png",
    logoFr: "/img/branding/cb-cda.png",
    logoTitleEn: "Copyright Board of Canada",
    logoTitleFr: "Commission du droit d'auteur du Canada",
  },
  {
    name: "tsb",
    urlEn: "https://www.tsb.gc.ca/eng/",
    urlFr: "https://www.tsb.gc.ca/fra",
    logoEn: "/img/branding/tsb-en.png",
    logoFr: "/img/branding/tsb-fr.png",
    logoTitleEn: "Transportation Safety Board of Canada",
    logoTitleFr: "Bureau de la sécurité des transports du Canada",
  },
  {
    name: "decced",
    urlEn: "https://ced.canada.ca",
    urlFr: "https://dec.canada.ca",
    logoEn: "/img/branding/decced-en.svg",
    logoFr: "/img/branding/decced-fr.svg",
    logoTitleEn: "Canada Economic Development for Quebec Regions",
    logoTitleFr: "Développement économique Canada pour les régions du Québec",
  },
  {
    name: "cds",
    urlEn: "https://digital.canada.ca",
    urlFr: "https://numerique.canada.ca",
    logoEn: "/img/branding/cds-en.svg",
    logoFr: "/img/branding/cds-fr.svg",
    logoTitleEn: "Canadian Digital Service",
    logoTitleFr: "Service numérique canadien",
  },
  {
    name: "cnsc",
    urlEn: "http://nuclearsafety.gc.ca/eng",
    urlFr: "http://nuclearsafety.gc.ca/fra",
    logoEn: "/img/branding/cnsc-en.svg",
    logoFr: "/img/branding/cnsc-fr.svg",
    logoTitleEn: "Canadian Nuclear Safety Commission",
    logoTitleFr: "Commission canadienne de sûreté nucléaire",
  },
  {
    name: "fintrac",
    urlEn: "https://fintrac-canafe.canada.ca/intro-eng",
    urlFr: "https://fintrac-canafe.canada.ca/intro-fra",
    logoEn: "/img/branding/fintrac-en.svg",
    logoFr: "/img/branding/fintrac-fr.svg",
    logoTitleEn: "Financial Transactions and Reports Analysis Centre of Canada",
    logoTitleFr: "Centre d’analyse des opérations et déclarations financières du Canada",
  },
  {
    name: "rcmp",
    urlEn: "https://www.rcmp-grc.gc.ca/en",
    urlFr: "https://www.rcmp-grc.gc.ca/fr",
    logoEn: "/img/branding/rcmp-en.svg",
    logoFr: "/img/branding/rcmp-fr.svg",
    logoTitleEn: "Royal Canadian Mounted Police",
    logoTitleFr: "Gendarmerie royale du Canada",
  },
  {
    name: "ssc",
    urlEn: "https://plus.ssc-spc.gc.ca/en",
    urlFr: "https://plus.ssc-spc.gc.ca/fr",
    logoEn: "/img/branding/ssc-en.svg",
    logoFr: "/img/branding/ssc-fr.svg",
    logoTitleEn: "Shared Services Canada",
    logoTitleFr: "Services partagés Canada",
  },
  {
    name: "feddevon",
    urlEn: "https://feddev-ontario.canada.ca/en",
    urlFr: "https://feddev-ontario.canada.ca/fr",
    logoEn: "/img/branding/fed-dev-ontario-en.svg",
    logoFr: "/img/branding/fed-dev-ontario-fr.svg",
    logoTitleEn: "Federal Economic Development Agency for Southern Ontario",
    logoTitleFr: "Agence fédérale de développement économique pour le Sud de l’Ontario",
  },
];
