export { prisma, prismaErrors } from "./client";
export {
  Prisma,
  PrismaClient,
  type Account,
  type ApiServiceAccount,
  type Session,
  type Template,
  type DeliveryOption,
  type Privilege,
  type User,
  type VerificationToken,
  type Setting,
  type CognitoCustom2FA,
  type SecurityQuestion,
  type SecurityAnswer,
  type MagicLink,
  type Invitation,
  type UserFeature,
} from "./generated/client";
