name: Cypress Component Tests
on:
  pull_request:
    branches: [main, feature/*]

jobs:
  cypress-run:
    name: Cypress Component Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Node.JS Setup
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: .nvmrc

      - name: Yarn update to V4
        run: corepack enable && yarn set version berry

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: linux-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            linux-yarn-

      - name: "Install dependencies"
        run: yarn workspaces focus gcforms flag_initialization

      - name: Cypress Component Tests
        uses: cypress-io/github-action@f1f0912d392f0d06bdd01fb9ebe3b3299e5806fb # v6.7.7
        with:
          # we have already installed all dependencies above
          install: false
          browser: chrome
          component: true
          headed: false
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
