name: E2E Tests
on:
  pull_request:
    branches: [develop, main, feature/*]

jobs:
  cypress-run:
    name: Cypress
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres@sha256:6d2a810d24786a90bf4bf2f4d4ce7a1039696a9269f3293abf3d6c8aa0bab9da
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        # Docker Hub image
        image: redis@sha256:94f604c382f8322bbc6c96bf87233e7379d4d2e4e3ed289394b6d6f0eeb7dfe6
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    env:
      # Needed for Next Auth to initialize
      TOKEN_SECRET: testKey
      APP_ENV: test
      NEXT_PUBLIC_APP_ENV: test
      REDIS_URL: localhost
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/formsDB
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v1.2.0
      - name: Node.JS Setup
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: .nvmrc

      - name: Yarn update to V4
        run: corepack enable && yarn set version berry

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: linux-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            linux-yarn-

      - name: "Install dependencies"
        run: yarn workspaces focus gcforms flag_initialization

      - name: Cypress Tests
        uses: cypress-io/github-action@1b70233146622b69e789ccdd4f9452adc638d25a # v6.6.1
        with:
          # we have already installed all dependencies above
          install: false
          browser: chrome
          headed: false
          build: yarn build:test
          start: yarn start:test
          wait-on: "http://localhost:3000"
          config: baseUrl=http://localhost:3000
      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # tag=v4.3.3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
