name: Generate SBOM

on:
  pull_request:
    branches:
      - main
    paths:
      - yarn.lock
      - .github/workflows/generate-sbom.yml
  push:
    branches:
      - main
    paths:
      - yarn.lock
      - .github/workflows/generate-sbom.yml

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0

      - name: Generate app SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@4368a5486da1f0bb698ffe717687612d4231c6cd # v1.1.7
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project_name: forms-client/app
          project_type: node      
