name: "Publish internal packages"

on:
  push:
    branches:
      - main
    paths:
      - "packages/**/package.json"

jobs:
  publish-internal-packages:
    name: "Publish internal packages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 2
          
      - name: Node.JS Setup
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"

      - name: Yarn update to V4
        run: corepack enable && yarn set version stable

      - run: yarn install
      - run: |
          changed_dirs=$(git diff --dirstat=files,0 HEAD~1 packages/ | cut -d'/' -f2 | sort -u)
          echo "Changed directories: $changed_dirs"
          echo "dirs=$(echo $changed_dirs | tr ' ' ',')" >> $GITHUB_ENV

          for dir in $(echo "${changed_dirs}" | tr ',' '\n'); do
            echo "Publishing package: $dir"
            cd packages/$dir
            yarn npm publish --access public
            cd ../..
          done
        env:
          YARN_NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
