name: Internal packages

on:
  pull_request:
    branches:
      - main

jobs:
  check-package-versions:
    name: Check package versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check package directories for changes
        id: changed-dirs
        run: |
          git fetch origin main:main
          git diff --dirstat=files,0 main...HEAD packages/ | cut -d'/' -f2 | sort -u
          changed_dirs=$(git diff --dirstat=files,0 main...HEAD packages/ | cut -d'/' -f2 | sort -u)
          echo "dirs=$(echo $changed_dirs | tr ' ' ',')" >> $GITHUB_OUTPUT

      - name: Check versions of changed packages
        if: steps.changed-dirs.outputs.dirs != ''
        run: |
          echo "Checking versions in packages with changes: ${{ steps.changed-dirs.outputs.dirs }}"
          status=0
          for dir in $(echo "${{ steps.changed-dirs.outputs.dirs }}" | tr ',' '\n'); do
            main_version=$(git show origin/main:packages/$dir/package.json | jq -r .version)
            current_version=$(jq -r .version packages/$dir/package.json)
            if [ "$main_version" != "$current_version" ]; then
              echo -e "✅ \033[0;32m$dir : Version has been updated from $main_version to $current_version\033[0m"
            else
                echo -e "☠️ \033[0;31m$dir : Version $current_version unchanged but changes detected in package\033[0m"
              status=-1
            fi
          done
          exit $status
