name: "Publish internal packages"

on:
  push:
    branches:
      - main
    paths:
      - "packages/**/package.json"

jobs:
  publish-internal-packages:
    name: "Publish internal packages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: |
          changed_dirs=$(git diff --dirstat=files,0 HEAD~1 packages/ | cut -d'/' -f2 | sort -u)
          echo "Changed directories: $changed_dirs"
          echo "dirs=$(echo $changed_dirs | tr ' ' ',')" >> $GITHUB_ENV

          for dir in $(echo "${changed_dirs}" | tr ',' '\n'); do
            echo "Publishing package: $dir"
            cd packages/$dir
            yarn npm publish --access public
            cd ../..
          done
        env:
          YARN_NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
