name: Check package version

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for specific label
        id: label-check
        uses: actions/github-script@v6
        with:
          script: |
            const label = '!! Package Update !!';
            const labels = context.payload.pull_request.labels.map(l => l.name);
            return labels.includes(label);

      - name: Run if label exists
        if: steps.label-check.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            git fetch origin main
            git checkout origin/main -- package.json
            diff package.json package.json
            if [ $? -eq 0 ]; then
              echo "Version in package.json has not changed."
              exit 1
            else
              echo "Version in package.json has changed."
            fi
