name: Check package version

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for specific label
        id: label-check
        uses: actions/github-script@v6
        with:
          script: |
            const label = '!! Package Update !!';
            const labels = context.payload.pull_request.labels.map(l => l.name);
            return labels.includes(label);

      - name: Get changed directories
        id: changed-dirs
        run: |
          git fetch origin main
          git --version
          changed_dirs=$(git diff --dirstat=files,0 main...HEAD packages/ | cut -d'/' -f2 | sort -u)
          echo "dirs={$changed_dirs}"  >> $GITHUB_OUTPUT

      # - name: Check versions of changed packages
      #   if: steps.label-check.outputs.result == 'true'
      #   run: |
      #     for dir in $(echo "${{ steps.changed-dirs.outputs.dirs }}" | tr ',' '\n'); do
      #     main_version=$(git show origin/main:packages/$dir/package.json | jq -r .version)
      #     current_version=$(jq -r .version packages/$dir/package.json)
      #     if [ "$main_version" != "$current_version" ]; then
      #       echo "Version mismatch in $dir: main branch version is $main_version, current branch version is $current_version"
      #       exit 1
      #     else
      #       echo "Version matches in $dir: $current_version"
      #     fi
      #       done

      # - name: Run if label exists
      #   if: steps.label-check.outputs.result == 'true'
      #   run: |
      #     git fetch origin main
      #     main_version=$(git show origin/main:package.json | jq -r .version)
      #     current_version=$(jq -r .version package.json)
      #     if [ "$main_version" != "$current_version" ]; then
      #       echo "Version mismatch: main branch version is $main_version, current branch version is $current_version"
      #       exit 1
      #     else
      #       echo "Version matches: $current_version"
      #       exit -1
      #     fi
