name: "Publish internal packages"

on:
  push:
    branches:
      - main
    paths:
      - "packages/**/package.json"

jobs:
  publish-internal-packages:
    name: "Publish internal packages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Install dependencies"
        run: yarn install

      - name: "Publish packages"
        run: |
          changed_dirs=$(git diff --dirstat=files,0 origin/main...HEAD packages/ | cut -d'/' -f2 | sort -u)
          echo "dirs=$(echo $changed_dirs | tr ' ' ',')" >> $GITHUB_ENV

          for dir in $(echo "${changed_dirs}" | tr ',' '\n'); do
            echo "Publishing package: $dir"
            cd packages/$dir
            # yarn publish --access public
            cd ../..
          done
