name: Prettify Code
on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Install prettier
        run: yarn install

      - name: Prettify code
        run: yarn format

      - name: Commit any changes
        uses: "docker://cdssnc/auto-commit-github-action"
        needs: ["Prettify Code"]
        args: "Prettified - Auto Commit"
        secrets: ["${{ secrets.GITHUB_TOKEN }}"]
