name: Prettify Code
on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install prettier
        run: yarn add prettier

      - name: Check code style
        run: yarn format:check
