name: "Production — Post deployment"

on:
  release:
    types: [published]

# Limit execution to 1 and also makes new trigger events cancel currently running workflow
concurrency:
  group: production-post-deployment
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  report-to-sentinel:
    runs-on: ubuntu-latest
    steps:
      - name: Report deployment to Sentinel
        uses: cds-snc/sentinel-forward-data-action@343498df663a056249bd96f260265aa80691b747 # main
        with:
          input_data: '{"product": "forms", "sha": "${{ github.sha }}", "version": "${{ github.ref_name }}", "repository": "${{ github.repository }}", "environment": "production", "status": "${{ job.status }}"}'
          log_type: CDS_Product_Deployment_Data
          log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
