on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Generator

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: sre_app_token
        with:
          app-id: ${{ secrets.SRE_APP_ID }}
          private-key: ${{ secrets.SRE_APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        with:
          token: ${{ steps.sre_app_token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
