on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

name: Release Generator

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@51ee8ae2605bd5ce1cfdcc5938684908f1cd9f69 # v3.7.9
        with:
          command: manifest
          token: ${{secrets.RELEASE_GENERATOR_TOKEN}}
          release-type: node
          default-branch: develop
