on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

name: Release Generator

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@86576b355dd19da0519e0bdb63d8edb5bcf76a25 # v1.7.0
        id: sre_app_token
        with:
          app_id: ${{ secrets.SRE_APP_ID }}
          private_key: ${{ secrets.SRE_APP_PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@a37ac6e4f6449ce8b3f7607e4d97d0146028dc0b # v4.1.0
        with:
          token: ${{ steps.sre_app_token.outputs.token }}
          release-type: node
          target-branch: develop
