name: Deploy to Sandbox

on:
  push:
    branches: [sandbox]

jobs:
  deploy-form-viewer-service:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for container to be built and pushed
        # v1.0.0 of this action as of Jan 28 2021
        uses: fountainhead/action-wait-for-check@4699210ccc66e2a13260803fadbb77085421b891
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: push-sandbox
          ref: ${{ github.sha }}

      - name: Checkout
        if: steps.wait-for-build.outputs.conclusion == 'success'
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        # v1 as of Jan 28 2021
        uses: aws-actions/configure-aws-credentials@51e2d042f8c5cf77f151685c9338e989dc0b8fc8
        with:
          aws-access-key-id: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SANDBOX_AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        # v1 as of Jan 28 2021
        uses: aws-actions/amazon-ecr-login@b9c809dc38d74cd0fde3c13cc4fe4ac72ebecdae

      - name: Get Cluster Name
        id: cluster
        run: |
          echo "##[set-output name=name;]$(aws ecs list-clusters | jq -r '.clusterArns[0]' | cut -f 2 -d "/" )"
      - name: Download Form Viewer task definition
        id: download-taskdef-form-viewer
        run: |
          aws ecs describe-task-definition --task-definition form-viewer --query taskDefinition > form_viewer.json
          echo "##[set-output name=container_name;]$(jq -r '.containerDefinitions[0].name' form_viewer.json)"
      - name: Render image for form viewer service
        id: taskdef-form-viewer
        # v1.0.10
        uses: aws-actions/amazon-ecs-render-task-definition@9666dc9d3bf790a3a6a49737b240f17fa599a5f2
        with:
          task-definition: form_viewer.json
          container-name: ${{ steps.download-taskdef-form-viewer.outputs.container_name }}
          image: ${{ steps.login-ecr.outputs.registry }}/form_viewer_sandbox:${{ github.sha }}

      - name: Render appspec for form viewer service
        run: |
          CONTAINER_PORT=`jq '.containerDefinitions[0].portMappings[0].containerPort' form_viewer.json`
          CONTAINER_NAME=${{ steps.download-taskdef-form-viewer.outputs.container_name }}
          TASKDEF_ARN=`jq -r '.taskDefinitionArn' form_viewer.json | cut -f 1-6 -d "/"`
          jq  --argjson port "$CONTAINER_PORT" --arg cname "$CONTAINER_NAME" --arg taskdefarn "$TASKDEF_ARN" '.Resources[0].TargetService.Properties.TaskDefinition = $taskdefarn | .Resources[0].TargetService.Properties.LoadBalancerInfo.ContainerName = $cname | .Resources[0].TargetService.Properties.LoadBalancerInfo.ContainerPort = $port' config/infrastructure/aws/appspec-template.json > form-viewer-appspec.json
      - name: Deploy image for Form Viewer
        timeout-minutes: 10
        # v1.4.2
        uses: aws-actions/amazon-ecs-deploy-task-definition@c74a8ca2cd0dd04d25f469715e23cb6c2fe0f01a
        with:
          task-definition: ${{ steps.taskdef-form-viewer.outputs.task-definition }}
          service: form-viewer
          cluster: ${{ steps.cluster.outputs.name }}
          wait-for-service-stability: true
          codedeploy-appspec: ${{ github.workspace }}/form-viewer-appspec.json
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
