name: "Staging — Post deployment"

on:
  push:
    branches: [main]
    paths-ignore:
      # Ignore all files and folders that start with '.'
      - ".**"
      # Ignore all files and folder in fixtures, tests, utils, etc.
      - "__*/**"
      - "tests/**"

# Limit execution to 1 and also makes new trigger events cancel currently running workflow
concurrency:
  group: staging-post-deployment
  cancel-in-progress: true

permissions:
  contents: write
  security-events: write

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Build Form Viewer
        run: |
          docker build --platform=linux/amd64 --provenance false -t forms-client \
            --build-arg COGNITO_APP_CLIENT_ID="COGNITO_APP_CLIENT_ID" \
            --build-arg COGNITO_USER_POOL_ID="COGNITO_USER_POOL_ID" \
            --build-arg HCAPTCHA_SITE_KEY="HCAPTCHA_SITE_KEY" \
            --build-arg ZITADEL_URL="ZITADEL_URL" \
            --build-arg ZITADEL_PROJECT_ID="ZITADEL_PROJECT_ID" \
            --build-arg API_URL="API_URL" \
            --build-arg NEXT_DEPLOYMENT_ID=$GITHUB_SHA .

      - name: Docker generate SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@837a88b6337d4842543184c8eac97a8adac8f302 # v4.0.3
        env:
          TRIVY_DB_REPOSITORY: ${{ vars.TRIVY_DB_REPOSITORY }}
        with:
          docker_image: "forms-client"
          dockerfile_path: "Dockerfile"
          token: "${{ secrets.GITHUB_TOKEN }}"

  report-to-sentinel:
    runs-on: ubuntu-latest
    steps:
      - name: Report deployment to Sentinel
        uses: cds-snc/sentinel-forward-data-action@343498df663a056249bd96f260265aa80691b747 # main
        with:
          input_data: '{"product": "forms", "sha": "${{ github.sha }}", "version": "${{ github.sha }}", "repository": "${{ github.repository }}", "environment": "staging", "status": "${{ job.status }}"}'
          log_type: CDS_Product_Deployment_Data
          log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
