name: Scan for security vulnerabilities (Weekly on Sunday)

on:
  schedule:
  - cron: "0 12 * * 0"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run scan websites
        run: |
          curl -s https://scan-websites.alpha.canada.ca > /dev/null
          sleep 60
          curl -X GET -H 'X-API-KEY: ${{ secrets.SCAN_WEBSITES_KEY }}' -H 'X-TEMPLATE-TOKEN: ${{ secrets.SCAN_WEBSITES_TEMPLATE }}' 'https://scan-websites.alpha.canada.ca/scans/start?dynamic=true'